version: "3"

services:
  zkpushtocc:
    build: .
    image: registry.cn-beijing.aliyuncs.com/right/zkpushtocc:1.0.0
    container_name: zkpushtocc_v1
    restart: always
    ports:
      - 5556:5556
    volumes:
      - "/opt/work/zkpushtocc_v1/Configs:/app/work/zkpushtocc_v1/Configs"
      - "/opt/work/zkpushtocc_v1/Configs/appsettings.json:/app/work/zkpushtocc_v1/appsettings.json"
      - "/opt/work/zkpushtocc_v1/logs:/app/work/zkpushtocc_v1/logs"
